"""empty message

Revision ID: 2d83210d0d03
Revises: 8bb6ef1c6af3
Create Date: 2025-09-28 12:32:25.058433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d83210d0d03'
down_revision = '8bb6ef1c6af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('media_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_firstname_key', type_='unique')
        batch_op.drop_constraint('user_lastname_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_lastname_key', ['lastname'])
        batch_op.create_unique_constraint('user_firstname_key', ['firstname'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('media_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
